apiVersion: v1
kind: Service
metadata:
  name: payments-service
  namespace: opslora-test-ns
spec:
  type: ClusterIP
  selector:
    app:payments-service
  ports:
  - port: 3000
    tragetPort: 3000
    protocol: tcp