name: Payment Pipeline

on:
  pull_request:
    types: [opened, synchronize, closed]

concurrency:
  group: opslora-payment-service-${{ github.repository }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:

  get-email:
    runs-on: ubuntu-latest
    outputs:
      email: ${{ steps.author.outputs.email }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: author
        run: |
          SHA="${{ github.event.pull_request.head.sha }}"
          EMAIL=$(git show -s --format='%ae' "$SHA")
          echo "email=$EMAIL" >> "$GITHUB_OUTPUT"

  sonar-scan:
    uses: ./.github/workflows/ci_sonar_scan.yml
    secrets: inherit

  snyk-scan:
    needs: sonar-scan
    if: ${{ needs.sonar-scan.outputs.quality_gate_status == 'PASSED' }}
    uses: ./.github/workflows/ci_snyk_scan.yml
    secrets: inherit

  # docker-build:
  #   needs: [sonar-scan, snyk-scan]
  #   if: >
  #     github.event.action == 'closed' &&
  #     github.event.pull_request.merged == true &&
  #     contains(github.event.pull_request.labels.*.name, 'build') &&
  #     needs.snyk-scan.outputs.snyk_status == 'success'
  #   uses: ./.github/workflows/ci-docker-build.yaml
  #   secrets: inherit

  # trivy-scan:
  #   needs: docker-build
  #   uses: ./.github/workflows/ci-trivy-scan.yaml
  #   with:
  #     image_tag: ${{ needs.docker-build.outputs.image_tag }}
  #   secrets: inherit

  notify:
    needs: [get-email, sonar-scan, snyk-scan]
    if: >
      always() &&
      (
        needs.sonar-scan.outputs.quality_gate_status == 'FAILED' ||
        needs.snyk-scan.outputs.snyk_status == 'failure' 
      )
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Sonar Notification
        if: ${{ needs.sonar-scan.outputs.quality_gate_status == 'FAILED' }}
        uses: ./.github/actions/notification-action
        with:
          pipeline_name: ${{ github.workflow }}
          repository_name: ${{ github.repository }}
          failure_reason: ${{ needs.sonar-scan.outputs.notify_summary }}
          author: ${{ github.event.pull_request.user.login }}
          smtp_username: ${{ secrets.SMTP_USERNAME }}
          smtp_password: ${{ secrets.SMTP_PASSWORD }}
          mail_from: ${{ secrets.MAIL_FROM }}
          mail_to: ${{ secrets.NOTIFY_EMAIL_TO }}
          slack_webhook: ${{ secrets.SLACK_INCOMING_WEBHOOK }}
          tool: sonar
          workflow_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          sonar_host_url: ${{ secrets.SONAR_HOST_URL }}
          sonar_project_key: ${{ secrets.SONAR_PROJECT_KEY }}

      - name: Snyk Notification
        if: ${{ needs.snyk-scan.outputs.snyk_status == 'failure' }}
        uses: ./.github/actions/notification-action
        with:
          pipeline_name: ${{ github.workflow }}
          repository_name: ${{ github.repository }}
          failure_reason: ${{ needs.snyk-scan.outputs.notify_summary }}
          author: ${{ github.event.pull_request.user.login }}
          smtp_username: ${{ secrets.SMTP_USERNAME }}
          smtp_password: ${{ secrets.SMTP_PASSWORD }}
          mail_from: ${{ secrets.MAIL_FROM }}
          mail_to: ${{ secrets.NOTIFY_EMAIL_TO }}
          slack_webhook: ${{ secrets.SLACK_INCOMING_WEBHOOK }}
          tool: snyk
          workflow_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          snyk_org: ${{ secrets.SNYK_ORG }}
          snyk_project_id: ${{ secrets.SNYK_PROJECT_ID }}

      # - name: Trivy Notification
      #   if: ${{ needs.trivy-scan.result == 'failure' }}
      #   uses: ./.github/actions/notification-action
      #   with:
      #     pipeline_name: ${{ github.workflow }}
      #     repository_name: ${{ github.repository }}
      #     failure_reason: "Container vulnerabilities detected (HIGH/CRITICAL)"
      #     author: ${{ github.event.pull_request.user.login }}
      #     smtp_username: ${{ secrets.SMTP_USERNAME }}
      #     smtp_password: ${{ secrets.SMTP_PASSWORD }}
      #     mail_from: ${{ secrets.MAIL_FROM }}
      #     mail_to: ${{ needs.get-email.outputs.email }}
      #     slack_webhook: ${{ secrets.SLACK_INCOMING_WEBHOOK }}
      #     tool: trivy
      #     workflow_url: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}